server:
  port: 8081

spring:
  redis:
    host: '43.201.111.5'
    password: '1234'
    port: 6379
  profiles:
    include: local
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB

  security:
    oauth2:
      client:
        registration:
          kakao:
            authorization-grant-type: authorization_code
            client-id: 693c5c83de59c1a45ea35b29b4de1933
            client-secret: wjEUwBMVAXEiASeRTsAsSzJX6tB2FYrk
            scope: account_email
            client-authentication-method: POST
            redirect-uri: 'http://localhost:8081/login/oauth2/code/social'
            client-name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    org:
      hibernate: info

token:
  secret: 'secretkey'

cloud:
  aws:
    credentials:
      accessKey: AKIAUX2TPRSSNLAUZYXB
      secretKey: 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
    region:
      static: ap-northeast-2
    s3:
      bucket : bangsilbangsil
    stack:
      auto: 'false'

mail:
  smtp:
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: 'false'
      port: '465'
    starttls:
      required: 'true'
      enable: 'true'
    port: '465'
    auth: 'true'

AdminMail:
  password: 'tocheck118!'
  id : 'sunjunam118@naver.com'
