server:
  port: 8081

spring:
  redis:
    host: '43.201.111.5'
    password: '1234'
    port: 6379
  profiles:
    include: prod
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB
logging:
  level:
    org:
      hibernate: info

token:
  secret: 'secretkey'

cloud:
  aws:
    credentials:
      accessKey: AKIAUX2TPRSSNLAUZYXB
      secretKey: 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
    region:
      static: ap-northeast-2
    s3:
      bucket : bangsilbangsil
    stack:
      auto: 'false'

mail:
  smtp:
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: 'false'
      port: '465'
    starttls:
      required: 'true'
      enable: 'true'
    port: '465'
    auth: 'true'

AdminMail:
  password: 'tocheck118!'
  id : 'sunjunam118@naver.com'
