server:
  port: 8081

spring:
  redis:
    host: ENC(Z2WJpR/z/cLuUpM3ZxdheNi8+aTcV/kK)
    password: ENC(Zr2bEyfTWn5jlrckRVnUxw==)
    port: 6379
  profiles:
    include: prod
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB

  security:
    oauth2:
      client:
        registration:
          kakao:
            authorization-grant-type: authorization_code
            client-id: ENC(mgHwdlJciKfhJAWgEZSHtlnOjwg9JTOTOJYZ+T5rNhEvL1yK1HlWfg1MyUxha/UJ)
            client-secret: ENC(MqoEVX2dDDGXW7lLDynYpwpwT8jbEXy66CHcleKj3Dpn5iIPuPeUnSTdMgBmGnOm)
            scope: account_email
            client-authentication-method: POST
            redirect-uri: 'http://localhost:8081/login/oauth2/code/social'
            client-name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    org:
      hibernate: info

token:
  secret: ENC(4+qZwm4yJeuW8bFmDuIYL6ukCBOR1jZE)

cloud:
  aws:
    credentials:
      accessKey: ENC(/sdHErwyjPs/Yz+Ti1IU0DJSnhE52Dog14WtH5VLuYE=)
      secretKey: ENC(TBctMDxqafI/LqnGRFj/ylb9gyDp93UeNKbzIDG7UVMhylFR4OIixwsCVYn6vSp4cOzjcH+Hb4I=)
    region:
      static: ap-northeast-2
    s3:
      bucket : ENC(XQbcPW2c+5POUqxeqVskxVzGYqh6IWUy)
    stack:
      auto: 'false'

mail:
  smtp:
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: 'false'
      port: '465'
    starttls:
      required: 'true'
      enable: 'true'
    port: '465'
    auth: 'true'

AdminMail:
  password: ENC(vV2bsbHWFPOBEzeW+uuAkqX+WYv9XFY8)
  id : ENC(z/ExtgKRA0HSFcrrvTby+SfY/iXD2ipeVsJoKeDs6TU=)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
